### ISSUE TITLE
syntax error when run "yanr seed"

### ISSUE THREAD

**Issue by 45592858** [ryands17/serverless-prisma#10]
D:\SevenFiles\MyWorks\SRC\liangtuo.cn\try\serverless-prisma-master>yarn seed
yarn run v1.22.10
$ dotenv -- node prisma/seed.ts
D:\SevenFiles\MyWorks\SRC\liangtuo.cn\try\serverless-prisma-master\prisma\seed.ts:1
import { config } from 'dotenv'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

-------------------------------------------
and when I try to run "yarn add dotenv", the console hold on below screen seems no any reponse.
(Windows 10, Node v12)
-------------------------------------------
[10/10] ⡀ @prisma/client                                                                                                                                                                      [-/10] ⡀ waiting...                                                                                                                                                                           [-/10] ⡀ waiting...                                                                                                                                                                           [-/10] ⢀ waiting...                                                                                                                                                                           [-/10] ⢀ waiting...

**Comment by ryands17** [comment]
Fixed in the latest branch. You will not need to install `dotenv` as `dotenv-cli` is already running in the command.
